# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # Use the official CircleCI Node orb
  # See: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2.0

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  release-app:
    jobs:
      - release:
          # Run this job only when a commit is pushed to the main branch.
          filters:
            branches:
              only:
                - main

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  release:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - node/install:
          node-version: "20"
      - run:
          name: "Install FPM enviroment"
          command: sudo apt-get install ruby-dev build-essential rpm && sudo gem i fpm -f
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Build App"
          command: npm run build
      - run:
          name: "Sign, Notarize and Release new Version"
          command: npm run publish
          environment:
            GITHUB_TOKEN: $GH_TOKEN

