name: Release Desktop App

on: pull_request
  # push:
  #   branches:
  #     - main

jobs:
  release:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Dont use cache as we never re-run this job
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Bun enviroment
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build App
        run: bun run build

      - name: Sign, Notarize and Release new Version
        run: bun run publish
        env:
          # Github token to release the app and upload assets to streamline-releases repo
          GITHUB_TOKEN: ${{ secrets.gh_token }}